resources:
  pipelines:
    - pipeline: trigger
      source: 'js-demo-service ci'
      trigger:
        enabled: true
        branches:
          include:
            - main
            - sandbox

  repositories:
    - repository: pipelines
      trigger: none
      type: git
      name: KioUtils/templates-pipelines
      ref: refs/heads/feat/v1.1

trigger: none

variables:
  - template: ./variables/shared.yml

stages:
  - stage: ProductionDeploy
    dependsOn: []
    condition: eq(variables['resources.pipeline.trigger.sourceBranch'], 'refs/heads/main')
    displayName: Production deployment
    pool:
      vmImage: ubuntu-latest
    variables:
      - template: ./variables/deploy.yml
        parameters:
          stage: production
          area: ${{ variables.area }}
          team: ${{ variables.team }}
          serviceName: ${{ variables.serviceName }}
          serviceConnection: asc-services-sandbox1
    jobs:
      - template: pipelines/cd.yml@pipelines
        parameters:
          stage: $(stage)
          environment: ${{ variables.environment }}
          serviceConnection: ${{ variables.serviceConnection }}
          resourceGroupName: $(resourceGroupName)
          functionAppName: $(functionAppName)
          functionAppType: $(functionAppType)
          functionAppSettings: $(functionAppSettings)
          apimName: $(apimName)

  - stage: SandboxDeploy
    dependsOn: []
    condition: eq(variables['resources.pipeline.trigger.sourceBranch'], 'refs/heads/main')
    displayName: Sandbox deployment
    pool:
      vmImage: ubuntu-latest
    variables:
      - template: ./variables/deploy.yml
        parameters:
          stage: sandbox
          area: ${{ variables.area }}
          team: ${{ variables.team }}
          serviceName: ${{ variables.serviceName }}
          serviceConnection: asc-services-sandbox1
    jobs:
      - template: pipelines/cd.yml@pipelines
        parameters:
          stage: $(stage)
          environment: ${{ variables.environment }}
          serviceConnection: ${{ variables.serviceConnection }}
          resourceGroupName: $(resourceGroupName)
          functionAppName: $(functionAppName)
          functionAppType: $(functionAppType)
          functionAppSettings: $(functionAppSettings)
          apimName: $(apimName)