resources:
  repositories:
    - repository: pipelines
      trigger: none
      type: git
      name: KioUtils/templates-pipelines
      ref: refs/heads/feat/v1.1

trigger:
  branches:
    include:
      - main
      - develop
      - sandbox
      - release/*
  paths:
    exclude:
      - .azure
      - wiki
      - docs
      - README.md

variables:
  - template: ./variables/shared.yml

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - name: stage
        value: production
  - ${{ else }}:
      - name: stage
        value: sandbox

stages:
  - template: pipelines/ci.yml@pipelines
    parameters:
      stage: $(stage)
      nodeVersion: '$(nodeVersion)'
