trigger: none

variables:
  - template: ./variables/shared.yml

stages:
  - stage: SandboxProvision
    dependsOn: []
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/sandbox')
    displayName: Sandbox provision
    pool:
      vmImage: ubuntu-latest
    variables:
      - template: ./variables/deploy.yml
        parameters:
          stage: production
          area: ${{ variables.area }}
          team: ${{ variables.team }}
          serviceName: ${{ variables.serviceName }}
          serviceConnection: asc-services-production
    jobs:
      - template: pipelines/infra-provision.yml@pipelines
        parameters:
          stage: $(stage)
          environment: ${{ variables.environment }}
          serviceConnection: ${{ variables.serviceConnection }}
          serviceName: $(serviceName)
          resourceGroupName: $(resourceGroupName)
          functionAppName: $(functionAppName)
          functionAppType: $(functionAppType)
          functionAppSettings: $(functionAppSettings)
          apimName: $(apimName)

  - stage: ProductionProvision
    dependsOn: []
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    displayName: Production provision
    pool:
      vmImage: ubuntu-latest
    variables:
      - template: ./variables/deploy.yml
        parameters:
          stage: sandbox
          area: ${{ variables.area }}
          team: ${{ variables.team }}
          serviceName: ${{ variables.serviceName }}
          serviceConnection: asc-services-sandbox
    jobs:
      - template: pipelines/infra-provision.yml@pipelines
        parameters:
          stage: $(stage)
          serviceName: $(serviceName)
          storageAccountName: $()
          serviceConnection: ${{ variables.serviceConnection }}
          functionAppType: $(functionAppType)
